language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
services:
  - mysql
  - postgresql
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - cp config/config.sample.php config/config.php
  - mysql -e 'create database sample_database;'
  - psql -c 'create database sample_database;' -U postgres
script:
  - vendor/bin/phpunit
  - vendor/bin/phpmd src/ text phpmd.xml